package main.entities;
// Generated 27/jul/2016 16:01:44 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

import main.utils.HibernateUtil;

/**
 * Equipas generated by hbm2java
 */
@Entity
@Table(name = "equipas", catalog = "betting")
public class Equipas implements java.io.Serializable {

	private String nome;
	private Date dcria;
	private Date daltera;
	private String pais;

	public Equipas() {
	}

	public Equipas(String nome) {
		this.nome = nome;
	}

	public Equipas(String nome, Date dcria, Date daltera,String pais) {
		this.nome = nome;
		this.dcria = dcria;
		this.daltera = daltera;
		this.pais = pais;
	}

	@Id

	@Column(name = "nome", unique = true, nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dcria", length = 10)
	public Date getDcria() {
		return this.dcria;
	}

	public void setDcria(Date dcria) {
		this.dcria = dcria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "daltera", length = 10)
	public Date getDaltera() {
		return this.daltera;
	}

	public void setDaltera(Date daltera) {
		this.daltera = daltera;
	}

	@Column(name = "pais",  length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	 public void add(){
	      Session session = HibernateUtil.getSessionFactory().openSession();
	      Transaction tx = null;
	      
	      try{
	         tx = session.beginTransaction();
	         this.setDcria(new Date());
	         
	         session.save(this);
	         tx.commit();
	         System.out.println("Equipa Adicionada -> "+this.toString());
	      }catch (HibernateException e) {
	         if (tx!=null) tx.rollback();
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	       
	      }
	     
	   }
	 public boolean exists(){
	      Session session = HibernateUtil.getSessionFactory().openSession();
	      
	 
	      try{
	      
	         Equipas equipa =   (Equipas)session.get(Equipas.class, this.getNome()); 
	         
	         if(equipa != null){
	        	 return true;
	         }else return false;
	      }catch (HibernateException e) {
	         
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	      }
		return false;
	   }
	 public void update(){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	      Transaction tx = null;
	      try{
	         tx = session.beginTransaction();
	      this.setDaltera(new Date());
			 session.update(this); 
	         tx.commit();
			  System.out.println("Equipa Atualizada -> "+this.toString());

	      }catch (HibernateException e) {
	         if (tx!=null) tx.rollback();
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	      }
	   }
	 public Equipas fromDB(){
			
			
			Session session = HibernateUtil.getSessionFactory().openSession();	 
		    try{
		    
		       Equipas equipa =   (Equipas)session.get(Equipas.class, this.getNome()); 
		       
		       if(equipa != null){
		      	 return equipa;
		       }else return null;
		    }catch (HibernateException e) {
		       
		       e.printStackTrace(); 
		    }finally {
		       session.close(); 
		    }
			return null;
		 }
	 @Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.getNome()+" " +this.getPais();
	}

}
