package main.entities;
// Generated 27/jul/2016 16:01:44 by Hibernate Tools 5.1.0.Alpha1

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List; 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jsoup.select.Evaluator.IsEmpty;

import main.utils.HibernateUtil;
import main.utils.Utils;

/**
 * Equipas generated by hbm2java
 */
@Entity
@Table(name = "equipas", catalog = "betting")
public class Equipas implements java.io.Serializable {

	private String nome;
	private Date dcria;
	private Date daltera;
	private String pais;
	private String valido;
	private String user;

	public Equipas() {
	}

	public Equipas(String nome) {
		this.nome = nome;
	}

	public Equipas(String nome, Date dcria, Date daltera,String pais) {
		this.nome = nome;
		this.dcria = dcria;
		this.daltera = daltera;
		this.pais = pais;
	}

	@Id

	@Column(name = "nome", unique = true, nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dcria", length = 10)
	public Date getDcria() {
		return this.dcria;
	}

	public void setDcria(Date dcria) {
		this.dcria = dcria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "daltera", length = 10)
	public Date getDaltera() {
		return this.daltera;
	}

	public void setDaltera(Date daltera) {
		this.daltera = daltera;
	}

	@Column(name = "pais",  length = 45)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}
	@Column(name = "valido",  length = 3)
	public String getValido() {
		return this.valido;
	}

	public void setValido(String valido) {
		this.valido = valido;
	}
	@Column(name = "user",  length = 10)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	 public void add(){
	      Session session = HibernateUtil.getSessionFactory().openSession();
	      Transaction tx = null;
	      
	      try{
	         tx = session.beginTransaction();
	         this.setDcria(new Date());
	         this.setValido("NAO");
	         session.save(this);
	         tx.commit();
	         System.out.println("Equipa Adicionada -> "+this.toString());
	      }catch (HibernateException e) {
	         if (tx!=null) tx.rollback();
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	       
	      }
	     
	   }
	 public boolean exists(){
	      Session session = HibernateUtil.getSessionFactory().openSession();
	      
	 
	      try{
	      
	         Equipas equipa =   (Equipas)session.get(Equipas.class, this.getNome()); 
	         
	         if(equipa != null){
	        	 return true;
	         }else return false;
	      }catch (HibernateException e) {
	         
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	      }
		return false;
	   }
	 public static List <Equipas> listAll(){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	      Transaction tx = null;
	      try{
	         tx = session.beginTransaction();
	         List equipas = session.createQuery("FROM Equipas").list(); 
	         session.close(); 
return  equipas;
	      }catch (HibernateException e) {
	         if (tx!=null) tx.rollback();
	         e.printStackTrace(); 
	      }finally {
	         
	      }
	   return null;
	 }
	 public static List <Equipas> getAll(){
		try {
			ArrayList<Equipas> list = new ArrayList<>();
			String sql ="";
			Connection conn = null;
			PreparedStatement stmt = null;
			Class.forName(Utils.JDBC_DRIVER);
			conn = DriverManager.getConnection(Utils.DB_URL, Utils.USER, Utils.PASS);
			sql = "select * from equipas";
			stmt = conn.prepareStatement(sql);
			
			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
			Equipas a = new Equipas();
			a.setNome(rs.getString("nome"));
			a.setPais(rs.getString("pais"));
			a.setUser(rs.getString("user"));
			a.setDaltera(rs.getDate("daltera"));
			a.setDcria(rs.getDate("dcria"));
			a.setValido(rs.getString("valido"));
			list.add(a);
				
			}
		return list;	
		}catch (Exception e) {
			return null;	
			}
			}
	 public static List <Equipas> search(String nome, String pais, String user, String valido){
		try {
			ArrayList<Equipas> list = new ArrayList<>();
			String sql ="";
			
			Connection conn = null;
			PreparedStatement stmt = null;
			Class.forName(Utils.JDBC_DRIVER);
			conn = DriverManager.getConnection(Utils.DB_URL, Utils.USER, Utils.PASS);
			sql = "select * from equipas where ";
			if(nome != null && !nome.isEmpty()){
				sql+="nome= '"+nome +"' and ";
			}
			if(pais != null && !pais.isEmpty()){
				sql+="pais= '"+pais +"' and ";
			}
			if(user != null && !user.isEmpty()){
				sql+="user= '"+user +"' and ";
			}
			if(valido != null && !valido.isEmpty()){
				sql+="valido= '"+valido +"' and ";
			}
			sql+= " 1=1";
			stmt = conn.prepareStatement(sql);
			
			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
			Equipas a = new Equipas();
			a.setNome(rs.getString("nome"));
			a.setPais(rs.getString("pais"));
			a.setUser(rs.getString("user"));
			a.setDaltera(rs.getDate("daltera"));
			a.setDcria(rs.getDate("dcria"));
			a.setValido(rs.getString("valido"));
			list.add(a);
				
			}
		return list;	
		}catch (Exception e) {
			return null;	
			}
			}
	 public void update(){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	      Transaction tx = null;
	      try{
	         tx = session.beginTransaction();
	      this.setDaltera(new Date());
			 session.update(this); 
	         tx.commit();
			  System.out.println("Equipa Atualizada -> "+this.toString());

	      }catch (HibernateException e) {
	         if (tx!=null) tx.rollback();
	         e.printStackTrace(); 
	      }finally {
	         session.close(); 
	      }
	   }
	 public Equipas fromDB(){
			
			
			Session session = HibernateUtil.getSessionFactory().openSession();	 
		    try{
		    
		       Equipas equipa =   (Equipas)session.get(Equipas.class, this.getNome()); 
		       
		       if(equipa != null){
		      	 return equipa;
		       }else return null;
		    }catch (HibernateException e) {
		       
		       e.printStackTrace(); 
		    }finally {
		       session.close(); 
		    }
			return null;
		 }
	 
	 public static List<String> getEquipas(){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	 try{
		    
		 
			 String hql = "select nome from Equipas";
		    	Query query = session.createQuery(hql);
		    
		    	List results = query.list();
		    	return results;
	   }catch (Exception e) {
	      
	      e.printStackTrace(); 
	   }finally {
	      session.close(); 
	   }
		return null;
	}
	 public static List<String> searchLike(String filtro){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	 try{
		    
		 
			 String hql = "select nome from Equipas where nome LIKE :name";
		    	Query query = session.createQuery(hql).setString("name", "%"+filtro+"%");
		    
		    	List results = query.list();
		    	return results;
	   }catch (Exception e) {
	      
	      e.printStackTrace(); 
	   }finally {
	      session.close(); 
	   }
		return null;
	}
	 public static List<String> search(String nome, String pais, String valido){
		 Session session = HibernateUtil.getSessionFactory().openSession();	
	 try{
		    
		 
			 String hql = "select nome from Equipas where ";
			 if(!nome.isEmpty()){
				 hql+=" nome LIKE :name";
				 }
			 if(!valido.isEmpty()){
				 hql+=" and valido = :val";
			 }
		    	Query query = session.createQuery(hql).setString("name", "%"+nome+"%");
		    
		    	List results = query.list();
		    	return results;
	   }catch (Exception e) {
	      
	      e.printStackTrace(); 
	   }finally {
	      session.close(); 
	   }
		return null;
	}
	 
	 @Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.getNome()+" " +this.getPais();
	}

}
