package main.entities;
// Generated 27/jul/2016 15:03:10 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JogosId generated by hbm2java
 */
@Embeddable
public class JogosId implements java.io.Serializable {

	private String casa;
	private String fora;
	private String data;

	public JogosId() {
	}

	public JogosId(String casa, String fora, String data) {
		this.casa = casa;
		this.fora = fora;
		this.data = data;
	}

	@Column(name = "casa", nullable = false, length = 20)
	public String getCasa() {
		return this.casa;
	}

	public void setCasa(String casa) {
		this.casa = casa;
	}

	@Column(name = "fora", nullable = false, length = 20)
	public String getFora() {
		return this.fora;
	}

	public void setFora(String fora) {
		this.fora = fora;
	}

	@Column(name = "data", nullable = false, length = 20)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JogosId))
			return false;
		JogosId castOther = (JogosId) other;

		return ((this.getCasa() == castOther.getCasa()) || (this.getCasa() != null && castOther.getCasa() != null
				&& this.getCasa().equals(castOther.getCasa())))
				&& ((this.getFora() == castOther.getFora()) || (this.getFora() != null && castOther.getFora() != null
						&& this.getFora().equals(castOther.getFora())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
						&& this.getData().equals(castOther.getData())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCasa() == null ? 0 : this.getCasa().hashCode());
		result = 37 * result + (getFora() == null ? 0 : this.getFora().hashCode());
		result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
		return result;
	}

}
